version: '3.6'
services:
  user_api:
    container_name: user_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user_api_db

  user_api_db:
    container_name: user_api_db
    image: postgres
    environment:
      POSTGRES_USER: perseus
      POSTGRES_PASSWORD: password
      POSTGRES_DB: perseus-user-db
      PGDATA: /data/postgres
    volumes:
      - user_api_db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - user_api_db
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - user_api_db
    restart: unless-stopped

networks:
  user_api_db:
    driver: bridge
  spring:
    driver: bridge

volumes:
  user_api:
  user_api_db:
  pgadmin: