server:
  port: 8080
spring:
  application:
    name: perseus-user-api
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/persues-user-db
    username: emmantoksjr
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
